### ISSUE TITLE
The problems encountered during code execution

### ISSUE THREAD

**Issue by HJ-Xu** [pvnieo/clover#1]
Hello, your work is very interesting. However, I noticed that the code you uploaded does not include a main.py file that can be run directly. How can I obtain the results mentioned in your paper?

**Comment by deepalchemist** [comment]
Please open an issue on github.

HJ-Xu ***@***.***> 于2024年7月13日周六 17:03写道：

**Comment by pvnieo** [comment]
Hi @HJ-Xu 

Can you please explain to me your use case? Are you working on a research project, or you just try to obtain a map between some non-rigid shapes, and wanted to try this method for it?

**Comment by pvnieo** [comment]
Closing the issue, feel free to open it if you have additional questions!
